'use client'
import './globals.css'
import { ThemeProvider } from 'next-themes'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TogleThemes from '@/components/TogleThemes'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider attribute="class">
                    <TogleThemes className="absolute right-5 top-5" />
                    <main className="flex bg-primary">
                        <Sidebar />
                        <div className="flex-1 p-4">{children}</div>
                    </main>
                </ThemeProvider>
            </body>
        </html>
    )
}
